export { default as Home } from './Home/Home'
export { default as Work } from './Work/Work'
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Error404 } from './Error404/Error404'
